### ISSUE TITLE
linux-arm64 初始化远程存储失败 

### ISSUE THREAD

**Issue by hkai1221** [LXY1226/MiraiOK#29]
环境为 termux 构建的linux环境
windows 和 linux-amd上正常
linux-arm64 提示初始化远程储存失败 

[05:45:06.9855] I MiraiOK 20200629.160938 running at linux-arm64
[05:45:06.9856] I 此程序以Affero GPL3.0协议发布，使用时请遵守协议
[05:45:06.9856] I 代码库: github.com/LXY1226/MiraiOK gitee.com/LXY1226/MiraiOK
[05:45:06.9872] I 未发现JRE，准备下载...
[05:45:06.9874] I 开始检查Mirai更新... 也可以通过创建.noupdate文件来禁用更新
[05:45:06.9904] W 初始化远程存储失败
[05:45:06.9905] E 无法下载Mirai版本信息
[05:45:06.9905] F 无法获取JRE，即将退出...
[05:45:06.9906] E 无法下载MiraiOK版本信息
panic: error in gathering JRE

goroutine 18 [running]:
main.checkJava.func1()
	/home/runner/work/MiraiOK/MiraiOK/checkJRE.go:34 +0xe4
created by main.checkJava
	/home/runner/work/MiraiOK/MiraiOK/checkJRE.go:26 +0xc8

**Comment by yakira-neko** [comment]
建议自己下个jre

**Comment by hkai1221** [comment]
> 建议自己下个jre

好的，我会去尝试，感谢建议。

**Comment by LXY1226** [comment]
Close旧版issue
