### ISSUE TITLE
 java.lang.IllegalStateException: type mismatch 10

### ISSUE THREAD

**Issue by xiaoshanw** [LXY1226/MiraiOK#3]
[INFO] [NETWORK ERROR] java.lang.IllegalStateException: type mismatch 10
        at moe.him188.jcekt.internal.JceInput.readJceLongValue(JceInput.kt:209)
        at moe.him188.jcekt.internal.JceDecoder.decodeTaggedLong(JceDecoder.kt:324)
        at moe.him188.jcekt.internal.JceDecoder.decodeTaggedLong(JceDecoder.kt:23)
        at kotlinx.serialization.internal.TaggedDecoder.decodeLongElement(Tagged.kt:223)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.StGroupRankInfo$$serializer.deserialize(TroopList.kt)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.StGroupRankInfo$$serializer.deserialize(TroopList.kt:94)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:225)
        at kotlinx.serialization.builtins.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16)
        at kotlinx.serialization.builtins.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)
        at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:87)
        at kotlinx.serialization.internal.ListLikeSerializer.readAll(CollectionSerializers.kt:83)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:31)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:45)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:225)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:153)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeNullableSerializableValue(Decoding.kt:231)
        at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableValue(Tagged.kt:153)
        at kotlinx.serialization.internal.TaggedDecoder$decodeNullableSerializableElement$1.invoke(Tagged.kt:233)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:243)
        at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:233)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.GetTroopListRespV2$$serializer.deserialize(TroopList.kt)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.GetTroopListRespV2$$serializer.deserialize(TroopList.kt:40)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:225)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:153)
        at moe.him188.jcekt.Jce.load(Jce.kt:47)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils__UtilsKt.readJceStruct(utils.kt:50)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils.readJceStruct(utils.kt:1)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils__UtilsKt$readUniPacket$1.invoke(utils.kt:63)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils__UtilsKt$readUniPacket$1.invoke(utils.kt)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils__UtilsKt.decodeUniRequestPacketAndDeserialize$SerializationUtils__UtilsKt(utils.kt:92)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils__UtilsKt.readUniPacket(utils.kt:60)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils.readUniPacket(utils.kt:1)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils__UtilsKt.readUniPacket$default(utils.kt:58)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils.readUniPacket$default(utils.kt:1)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.list.FriendList$GetTroopListSimplify.decode(FriendList.kt:83)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:488)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:228)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:465)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:460)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:449)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by LXY1226** [comment]
啊
tx得协议更新了，mamoe群大佬刚修完
删掉.lastupdate然后重启miraiok，应该会自动下新版

**Comment by fzls** [comment]
> 啊
> tx得协议更新了，mamoe群大佬刚修完
> 删掉.lastupdate然后重启miraiok，应该会自动下新版

今天我在mirai那边也问了下，好像已经推送1.0.3版本啦。试了下ok了，打开miraiok就可以自动更新了，不过得手动删除1.0.2版本的内容

**Comment by LXY1226** [comment]
> > 啊
> > tx得协议更新了，mamoe群大佬刚修完
> > 删掉.lastupdate然后重启miraiok，应该会自动下新版
> 
> 今天我在mirai那边也问了下，好像已经推送1.0.3版本啦。试了下ok了，打开miraiok就可以自动更新了，不过得手动删除1.0.2版本的内容

啊
以一种极为简单~~懒~~的方式修了，过几~~亿~~天会出新console三件套，那时候再折腾更复杂的辞旧迎新。
