### ISSUE TITLE
arm版运行下载相关文件失败

### ISSUE THREAD

**Issue by Zeen-x** [LXY1226/MiraiOK#43]
网络状况良好，尝试过梯子
```linux
2020-09-11 20:xx:50 I/MiraiOK: MiraiOK 20200906.200346 linux-arm
2020-09-11 20:xx:50 I/MiraiOK: 此程序以Affero GPL3.0协议发布，使用时请遵守协议
2020-09-11 20:xx:50 I/MiraiOK: 部分开源于: github.com/LXY1226/MiraiOK
2020-09-11 20:xx:50 I/MiraiOK: 未发现JRE，准备下载...
2020-09-11 20:xx:50 I/MiraiOK: 读取库列表出现错误 open libs/version.txt: no such file or directory
2020-09-11 20:xx:50 I/MiraiOK: 开始检查Mirai更新... 也可以通过创建.noupdate文件来禁用更新
2020-09-11 20:xx:51 W/MiraiOK: 下载失败 MiraiOK/.version
2020-09-11 20:xx:51 E/MiraiOK: 无法下载MiraiOK版本信息
2020-09-11 20:xx:51 W/MiraiOK: 下载失败 shadow/latest.txt
2020-09-11 20:xx:51 E/MiraiOK: 无法下载Mirai版本信息
2020-09-11 20:xx:51 W/MiraiOK: 下载失败 MiraiOK/jre-linux-arm.rar
2020-09-11 20:xx:51 E/MiraiOK: 无法获取JRE，即将退出...
panic: error in gathering JRE

goroutine 18 [running]:
main.checkJava.func1()
	/home/runner/work/MiraiOK/MiraiOK/checkJRE.go:33 +0xb4
created by main.checkJava
	/home/runner/work/MiraiOK/MiraiOK/checkJRE.go:25 +0xa8

```

**Comment by ZYT2333** [comment]
咋整的，现在好了没
