### ISSUE TITLE
mirai补全依赖时错误

### ISSUE THREAD

**Issue by justghostof** [LXY1226/MiraiOK#44]
报错如下，Linux64版本使用wsl测试
可能原因：最新版链接未更新，旧版自动更新失败
Win64
```
2020-09-11 21:03:38 I/MiraiOK: MiraiOK 20200906.200346 windows-amd64
2020-09-11 21:03:38 I/MiraiOK: 此程序以Affero GPL3.0协议发布，使用时请遵守协议
2020-09-11 21:03:38 I/MiraiOK: 部分开源于: github.com/LXY1226/MiraiOK
2020-09-11 21:03:38 I/MiraiOK: openjdk version "11" 2018-09-25
2020-09-11 21:03:38 I/MiraiOK: OpenJDK Runtime Environment 18.9 (build 11+28)
2020-09-11 21:03:38 I/MiraiOK: OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
.jar: The filename, directory name, or volume label syntax is incorrect.
2020-09-11 21:03:38 I/MiraiOK: 开始检查Mirai更新... 也可以通过创建.noupdate文件来禁用更新
2020-09-11 21:03:39 W/MiraiOK: 下载失败 MiraiOK/.version
2020-09-11 21:03:39 E/MiraiOK: 无法下载MiraiOK版本信息
2020-09-11 21:03:39 W/MiraiOK: 下载失败 shadow/latest.txt
2020-09-11 21:03:39 E/MiraiOK: 无法下载Mirai版本信息
.jar;libs/core-qqandroid-1.2.20-M3-1
2020-09-11 21:03:39 I/MiraiOK: 启动Mirai...
错误: 找不到或无法加载主类 net.mamoe.mirai.console.pure.MiraiConsolePureLoader
原因: java.lang.ClassNotFoundException: net.mamoe.mirai.console.pure.MiraiConsolePureLoader
2020/09/11 21:03:39 java退出，exit status 1
2020-09-11 21:03:39 E/MiraiOK: 运行失败，尝试更新mirai三件套 exit status 1
2020-09-11 21:03:39 I/MiraiOK: 开始检查Mirai更新... 也可以通过创建.noupdate文件来禁用更新
2020-09-11 21:03:39 W/MiraiOK: 下载失败 shadow/latest.txt
2020-09-11 21:03:39 E/MiraiOK: 无法下载Mirai版本信息
2020-09-11 21:03:39 W/MiraiOK: 请重新启动MiraiOK
2020-09-11 21:03:39 I/MiraiOK: 按任意键退出

```
WIN32
```
2020-09-11 21:04:04 I/MiraiOK: MiraiOK 20200906.200346 windows-386
2020-09-11 21:04:04 I/MiraiOK: 此程序以Affero GPL3.0协议发布，使用时请遵守协议
2020-09-11 21:04:04 I/MiraiOK: 部分开源于: github.com/LXY1226/MiraiOK
2020-09-11 21:04:04 W/MiraiOK: 下载失败 MiraiOK/jre-windows-386.rar
2020-09-11 21:04:04 E/MiraiOK: 无法获取JRE，即将退出...
```
Linux64
```
2020-09-11 21:04:57 I/MiraiOK: MiraiOK 20200906.200346 linux-amd64
2020-09-11 21:04:57 I/MiraiOK: 此程序以Affero GPL3.0协议发布，使用时请遵守协议
2020-09-11 21:04:57 I/MiraiOK: 部分开源于: github.com/LXY1226/MiraiOK
2020-09-11 21:04:57 I/MiraiOK: openjdk version "11.0.8" 2020-07-14
2020-09-11 21:04:57 I/MiraiOK: OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
2020-09-11 21:04:57 I/MiraiOK: OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)
.jar: no such file or directoryre-1.0-M3-1ibs/console-pure-1.0-M3-1
2020-09-11 21:04:57 I/MiraiOK: 开始检查Mirai更新... 也可以通过创建.noupdate文件来禁用更新
2020-09-11 21:05:01 W/MiraiOK: 下载失败 shadow/latest.txt
2020-09-11 21:05:01 E/MiraiOK: 无法下载Mirai版本信息
.jar:libs/core-qqandroid-1.2.20-M3-1
2020-09-11 21:05:01 I/MiraiOK: 启动Mirai...
2020-09-11 21:05:01 W/MiraiOK: 下载失败 MiraiOK/.version
2020-09-11 21:05:01 E/MiraiOK: 无法下载MiraiOK版本信息
Error: Could not find or load main class net.mamoe.mirai.console.pure.MiraiConsolePureLoader
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.console.pure.MiraiConsolePureLoader
2020/09/11 21:05:01 java退出，exit status 1
2020-09-11 21:05:01 E/MiraiOK: 运行失败，尝试更新mirai三件套 exit status 1
2020-09-11 21:05:01 I/MiraiOK: 开始检查Mirai更新... 也可以通过创建.noupdate文件来禁用更新
2020-09-11 21:05:01 W/MiraiOK: 下载失败 shadow/latest.txt
2020-09-11 21:05:01 E/MiraiOK: 无法下载Mirai版本信息
2020-09-11 21:05:01 W/MiraiOK: 请重新启动MiraiOK
2020-09-11 21:05:01 I/MiraiOK: 按任意键退出
```

```

**Comment by find-xposed-magisk** [comment]
+1

**Comment by Stone-wh** [comment]
+1 如何解决那

**Comment by DancingSnow0517** [comment]
+1
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.main(MiraiConsolePureLoader.kt)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 1 more
2020/11/22 00:20:56 java退出，exit status 1
2020-11-22 xx:20:56 E/MiraiOK: 运行失败，尝试更新mirai三件套 exit status 1
2020-11-22 xx:20:56 I/MiraiOK: 同步最新库列表...
2020-11-22 xx:20:57 W/MiraiOK: 请重新启动MiraiOK
2020-11-22 xx:20:57 I/MiraiOK: 按任意键退出

**Comment by xiaoyv404** [comment]
+1

**Comment by xiaoyv404** [comment]
> +1

2020-12-19 09:30:43 I/MiraiOK: MiraiOK 20200915.071520 windows-amd64
2020-12-19 09:30:43 I/MiraiOK: 此程序以Affero GPL3.0协议发布，使用时请遵守协议
2020-12-19 09:30:43 I/MiraiOK: 部分开源于: github.com/LXY1226/MiraiOK
2020-12-19 09:30:43 I/MiraiOK: java version "1.8.0_261"
2020-12-19 09:30:43 I/MiraiOK: Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
2020-12-19 09:30:43 I/MiraiOK: Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)
2020-12-19 09:30:43 W/MiraiOK: 读取库列表失败 open libs/version.txt: The system cannot find the file specified.
2020-12-19 09:30:43 I/MiraiOK: 删除.lastupdate来在下次启动时强制检查更新
2020-12-19 09:30:43 I/MiraiOK: 启动Mirai...
错误: 找不到或无法加载主类 net.mamoe.mirai.console.pure.MiraiConsolePureLoader
2020/12/19 09:30:44 java退出，exit status 1
2020-12-19 09:30:44 E/MiraiOK: 运行失败，尝试更新mirai三件套 exit status 1
2020-12-19 09:30:44 I/MiraiOK: 同步最新库列表...
2020-12-19 09:30:45 W/MiraiOK: 下载失败 shadow/latest.txt
2020-12-19 09:30:45 E/MiraiOK: 无法下载库列表
2020-12-19 09:30:45 W/MiraiOK: 读取库列表失败 open libs/version.txt: The system cannot find the file specified.
2020-12-19 09:30:45 W/MiraiOK: 请重新启动MiraiOK
2020-12-19 09:30:45 I/MiraiOK: 按任意键退出
