### ISSUE TITLE
Linux下用wine部署Dice出现Dice! has been loaded with code 126

### ISSUE THREAD

**Issue by akhialomgir** [LXY1226/MiraiOK#50]
您好，wine是我。我使用的环境是Ubuntu 20.04。下面是终端输出信息。

```
$ wine MiraiOK.exe 
[16:40:24.8753] I MiraiOK 20200629.160938 running at windows-386
[16:40:24.8755] I 此程序以Affero GPL3.0协议发布，使用时请遵守协议
[16:40:24.8755] I 代码库: github.com/LXY1226/MiraiOK gitee.com/LXY1226/MiraiOK
[16:40:24.8756] D 如你所愿开启MiraiOK调试输出
[16:40:24.8756] I 如你所愿不会更新Mirai本体
[16:40:24.8758] D Trying Locating JRE: ./jre/bin/java
[16:40:25.4289] I JRE: openjdk version "1.8.0_252"
[16:40:25.4290] I JRE: OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
[16:40:25.4291] I JRE: OpenJDK Client VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)
[16:40:25.4296] D -jar mirai-console-wrapper-1.3.0.jar --update keep
[16:40:25.4297] I 启动Mirai...
Using proxy: null
You are running Mirai-Console-Wrapper under Z:\home\akhia\mirai
All additional libraries are located at Z:\home\akhia\mirai\libraries
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version ..
Stay on current version.
Fetching Newest Console Version of Pure
Stay on current version.
Version check complete, starting Mirai
shadow-Protocol:Z:\home\akhia\mirai\content\mirai-core-qqandroid-1.2.1.jar
Console        :Z:\home\akhia\mirai\content\mirai-console-0.5.2.jar
Root           :Z:\home\akhia\mirai/
 16:40:28 [INFO] [Mirai 0.5.2 Pkmon] Mirai-console now running under Z:\home\akhia\mirai
 16:40:28 [INFO] [Mirai 0.5.2 Pkmon] Get news in github: https://github.com/mamoe/mirai
 16:40:28 [INFO] [Mirai 0.5.2 Pkmon] Mirai?????????????????
 16:40:28 [INFO] [Mirai 0.5.2 Pkmon] Powered by Mamoe Technologies and contributors
 16:40:28 [INFO] [Plugin Manager] ????Z:\home\akhia\mirai/plugins/????
 16:40:29 [INFO] [Plugin Manager] loading plugin MiraiNative
 16:40:30 [INFO] [Plugin Manager] successfully loaded plugin MiraiNative version 1.8.6 by iTX Technologies
 16:40:30 [INFO] [Plugin Manager] ??? Mirai ???????
004f:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
004f:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
 16:40:30 [ERROR] [MiraiNative] java.lang.InternalError: couldn't create component peer
        at sun.awt.windows.WComponentPeer.checkCreation(WComponentPeer.java:822)
        at sun.awt.windows.WComponentPeer.<init>(WComponentPeer.java:793)
        at sun.awt.windows.WCanvasPeer.<init>(WCanvasPeer.java:45)
        at sun.awt.windows.WPanelPeer.<init>(WPanelPeer.java:74)
        at sun.awt.windows.WWindowPeer.<init>(WWindowPeer.java:171)
        at sun.awt.windows.WFramePeer.<init>(WFramePeer.java:181)
        at sun.awt.windows.WToolkit.createFrame(WToolkit.java:418)
        at java.awt.Frame.addNotify(Frame.java:477)
        at sun.awt.windows.WTrayIconPeer.<init>(WTrayIconPeer.java:62)
        at sun.awt.windows.WToolkit.createTrayIcon(WToolkit.java:538)
        at java.awt.TrayIcon.addNotify(TrayIcon.java:691)
        at java.awt.SystemTray.add(SystemTray.java:276)
        at org.itxtech.mirainative.ui.Tray.create(Tray.kt:52)
        at org.itxtech.mirainative.MiraiNative.onLoad(MiraiNative.kt:103)
        at net.mamoe.mirai.console.plugins.PluginBase.load$mirai_console(PluginBase.kt:137)
        at net.mamoe.mirai.console.plugins.PluginManager.loadPluginsImpl$mirai_console(PluginManager.kt:319)
        at net.mamoe.mirai.console.plugins.PluginManager.loadPlugins(PluginManager.kt:79)
        at net.mamoe.mirai.console.plugins.PluginManager.loadPlugins$default(PluginManager.kt:79)
        at net.mamoe.mirai.console.MiraiConsole.start(MiraiConsole.kt:131)
        at net.mamoe.mirai.console.MiraiConsole.start$default(MiraiConsole.kt:113)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader$Companion.load(MiraiConsolePureLoader.kt:22)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.load(MiraiConsolePureLoader.kt)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.mamoe.mirai.console.wrapper.WrapperMain.start$mirai_console_wrapper(WrapperMain.kt:236)
        at net.mamoe.mirai.console.wrapper.WrapperMain.preStartInNonNative$mirai_console_wrapper(WrapperMain.kt:207)
        at net.mamoe.mirai.console.wrapper.WrapperCli.run(WrapperMain.kt:143)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:154)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:14)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:252)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:249)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:267)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:290)
        at net.mamoe.mirai.console.wrapper.WrapperMain.main(WrapperMain.kt:176)

 16:40:31 [INFO] [MiraiNative] ???? Z:\home\akhia\mirai\plugins\MiraiNative\CQP.dll
 16:40:31 [INFO] [Plugin Manager] ???1???
 16:40:31 [INFO] [Mirai 0.5.2 Pkmon] Mirai-console ????
 16:40:31 [INFO] [Mirai 0.5.2 Pkmon] "login qqnumber qqpassword " to login a bot
 16:40:31 [INFO] [Mirai 0.5.2 Pkmon] "login qq? qq?? " ?????BOT
 16:40:31 [ERROR] [MiraiNative] Native Plugin (w json) Dice! has been loaded with code 126
```

**Comment by LXY1226** [comment]
No support for older version
