### ISSUE TITLE
0089:err:winediag:X11DRV_WineGL_InitOpenglInfo Direct rendering is disabled, most likely your 32-bit OpenGL drivers haven't been installed correctly (using GL renderer "Mesa GLX Indirect", version "1.3 Mesa 4.0.4").

### ISSUE THREAD

**Issue by akhialomgir** [LXY1226/MiraiOK#51]
java苦手です、教えてください、どうしたらいいですか、トラブル！

```shell
$ wine miraiOK_windows-386.exe 
2020-10-04 08:48:01 I/MiraiOK: MiraiOK 20200915.071520 windows-386
2020-10-04 08:48:01 I/MiraiOK: \u6b64\u7a0b\u5e8f\u4ee5Affero GPL3.0\u534f\u8bae\u53d1\u5e03\uff0c\u4f7f\u7528\u65f6\u8bf7\u9075\u5b88\u534f\u8bae
2020-10-04 08:48:01 I/MiraiOK: \u90e8\u5206\u5f00\u6e90\u4e8e: github.com/LXY1226/MiraiOK
2020-10-04 08:48:01 I/MiraiOK: JRE: openjdk version "1.8.0_252"
2020-10-04 08:48:01 I/MiraiOK: JRE: OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
2020-10-04 08:48:01 I/MiraiOK: JRE: OpenJDK Client VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)
2020-10-04 08:48:01 I/MiraiOK: \u5220\u9664.lastupdate\u6765\u5728\u4e0b\u6b21\u542f\u52a8\u65f6\u5f3a\u5236\u68c0\u67e5\u66f4\u65b0
2020-10-04 08:48:01 I/MiraiOK: \u542f\u52a8Mirai...
2020-10-04 08:48:02 I/main: Starting mirai-console...
2020-10-04 08:48:02 I/main: Backend: version 1.0-M4, built on 2020-09-13 02:19:35.
2020-10-04 08:48:02 I/main: Frontend Pure: version 1.0-M4, provided by Mamoe Technologies
2020-10-04 08:48:02 V/main: Loading configurations...
2020-10-04 08:48:05 V/main: Loading JVM plugins...
2020-10-04 08:48:05 I/plugin: Successfully loaded plugin MiraiNative
2020-10-04 08:48:05 V/main: 0 external PluginLoader(s) found. 
2020-10-04 08:48:05 V/main: 1 plugin(s) loaded.
2020-10-04 08:48:05 V/main: Loading PermissionService...
2020-10-04 08:48:05 V/main: Reloaded PermissionService settings.
2020-10-04 08:48:05 V/main: Loading built-in commands...
2020-10-04 08:48:05 V/main: Prepared built-in commands: help, login, permission, stop
2020-10-04 08:48:05 V/main: Enabling plugins...


0089:err:winediag:X11DRV_WineGL_InitOpenglInfo Direct rendering is disabled, most likely your 32-bit OpenGL drivers haven't been installed correctly (using GL renderer "Mesa GLX Indirect", version "1.3 Mesa 4.0.4").
0089:err:wgl:init_opengl  glx_version is 1.2 and GLX_SGIX_fbconfig extension is unsupported. Expect problems.
0089:err:wgl:init_pixel_formats glXChooseFBConfig returns NULL
0089:err:d3d:wined3d_caps_gl_ctx_create Failed to find a suitable pixel format.
0089:err:d3d:wined3d_adapter_gl_init Failed to get a GL context for adapter 0x63c238.

2020-10-04 08:48:06 I/MiraiNative: \u6b63\u5728\u52a0\u8f7d Mirai Native Bridge Z:\home\akhia\mirai\.\data\MiraiNative\CQP.dll
2020-10-04 08:48:06 E/MiraiNative: java.lang.NoSuchMethodError: net.mamoe.mirai.console.command.CompositeCommand.<init>(Lnet/mamoe/mirai/console/command/CommandOwner;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Lnet/mamoe/mirai/console/permission/Permission;ZLnet/mamoe/mirai/console/command/description/CommandArgumentContext;ILkotlin/jvm/internal/DefaultConstructorMarker;)V
java.lang.NoSuchMethodError: net.mamoe.mirai.console.command.CompositeCommand.<init>(Lnet/mamoe/mirai/console/command/CommandOwner;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Lnet/mamoe/mirai/console/permission/Permission;ZLnet/mamoe/mirai/console/command/description/CommandArgumentContext;ILkotlin/jvm/internal/DefaultConstructorMarker;)V
	at org.itxtech.mirainative.manager.PluginManager$NpmCommand.<init>(PluginManager.kt:210)
	at org.itxtech.mirainative.manager.PluginManager$NpmCommand.<clinit>(PluginManager.kt:210)
	at org.itxtech.mirainative.manager.PluginManager.registerCommands(PluginManager.kt:338)
	at org.itxtech.mirainative.MiraiNative.onEnable(MiraiNative.kt:168)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:100)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
	at net.mamoe.mirai.console.plugin.PluginManager.enable(PluginManager.kt:129)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:168)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:192)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:184)
	at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.startAsDaemon(MiraiConsolePureLoader.kt:150)
	at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.startAsDaemon$default(MiraiConsolePureLoader.kt:149)
	at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.main(MiraiConsolePureLoader.kt:46)


2020-10-04 08:48:06 I/main: 1 plugin(s) enabled.
2020-10-04 08:48:06 I/main: mirai-console started successfully.
```

**Comment by akhialomgir** [comment]
```shell
akhia@iZgg87k0lfgo9sZ:~/mirai$ export LIBGL_DRIVERS_PATH=/usr/lib32/dri
```

```shell

00b3:err:winediag:X11DRV_WineGL_InitOpenglInfo Direct rendering is disabled, most likely your 32-bit OpenGL drivers haven't been installed correctly (using GL renderer "Mesa GLX Indirect", version "1.3 Mesa 4.0.4").
00b3:err:wgl:init_opengl  glx_version is 1.2 and GLX_SGIX_fbconfig extension is unsupported. Expect problems.
00b3:err:wgl:init_pixel_formats glXChooseFBConfig returns NULL
00b3:err:d3d:wined3d_caps_gl_ctx_create Failed to find a suitable pixel format.
00b3:err:d3d:wined3d_adapter_gl_init Failed to get a GL context for adapter 0x63c238.

2020-10-04 12:22:46 I/MiraiNative: \u6b63\u5728\u52a0\u8f7d Mirai Native Bridge Z:\home\akhia\mirai\.\data\MiraiNative\CQP.dll
2020-10-04 12:22:46 E/MiraiNative: java.lang.NoSuchMethodError: net.mamoe.mirai.console.command.CompositeCommand.<init>(Lnet/mamoe/mirai/console/command/CommandOwner;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Lnet/mamoe/mirai/console/permission/Permission;ZLnet/mamoe/mirai/console/command/description/CommandArgumentContext;ILkotlin/jvm/internal/DefaultConstructorMarker;)V
java.lang.NoSuchMethodError: net.mamoe.mirai.console.command.CompositeCommand.<init>(Lnet/mamoe/mirai/console/command/CommandOwner;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Lnet/mamoe/mirai/console/permission/Permission;ZLnet/mamoe/mirai/console/command/description/CommandArgumentContext;ILkotlin/jvm/internal/DefaultConstructorMarker;)V
	at org.itxtech.mirainative.manager.PluginManager$NpmCommand.<init>(PluginManager.kt:210)
	at org.itxtech.mirainative.manager.PluginManager$NpmCommand.<clinit>(PluginManager.kt:210)
	at org.itxtech.mirainative.manager.PluginManager.registerCommands(PluginManager.kt:338)
	at org.itxtech.mirainative.MiraiNative.onEnable(MiraiNative.kt:168)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:100)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
	at net.mamoe.mirai.console.plugin.PluginManager.enable(PluginManager.kt:129)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:168)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:192)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:184)
	at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.startAsDaemon(MiraiConsolePureLoader.kt:150)
	at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.startAsDaemon$default(MiraiConsolePureLoader.kt:149)
	at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.main(MiraiConsolePureLoader.kt:46)
```

**Comment by sam01101** [comment]
Try another version of mirai (Like compiled binary) since this is not active usually
