### ISSUE TITLE
新旧版本miraoOK遇到的问题

### ISSUE THREAD

**Issue by apuded** [LXY1226/MiraiOK#52]
旧版本miraiOK问题：守护进程（nohup ./miraiOK_linux_amd64 nohup）运行几天必然挂掉
旧版本miraOK使用的jar组合（miraiOK运行后产生的）：
mirai-console-0.5.2.jar  
mirai-core-qqandroid-1.1.3.jar
mirai-console-wrapper-1.3.0.jar
旧版本大概是前几个月使用的，以下是进程突然挂掉时的日志输出：
[00:19:33.3608] E 运行失败，尝试更新mirai三件套 signal: killed
[00:19:34.5741] E 无法下载Mirai版本信息
[00:19:34.5741] E 无法启动 exec: already started
[07:33:19.8459] E 无法下载MiraiOK版本信息
[07:33:19.8620] E 无法下载Mirai版本信息

由于旧版本的不稳定，于是昨晚更新到miraiOK最新版本：
新版本miraiOK遇到的问题：疯狂输出错误日志
默认version.txt为：
mirai-console:1.0-M4
mirai-console-pure:1.0-M4
mirai-core-qqandroid:1.2.3
运行一晚后，产生了nohup文件共8G多，都是些java语法报错，不知道有没有人遇到这个问题。
开始怀疑是mirai-core-qqandroid版本不是最新的问题，于是更新至1.3.0，同样也是这个问题……

以下是部分报错信息
	at org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:946)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:637)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:454)
	at net.mamoe.mirai.console.pure.ConsoleInputImpl$requestInput$2.invokeSuspend(MiraiConsoleImplementationPure.kt:103)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.IOException: Bad file descriptor
	at java.io.FileInputStream.read0(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:207)
	at org.jline.utils.NonBlockingInputStreamImpl.run(NonBlockingInputStreamImpl.java:216)
	at java.lang.Thread.run(Thread.java:748)
> 2020-10-05 08:43:33 E/console: Unhandled exception
java.io.IOError: java.io.IOException: Bad file descriptor
	at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:170)
	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:110)
	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:61)
	at org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:913)
	at org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:946)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:637)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:454)
	at net.mamoe.mirai.console.pure.ConsoleInputImpl$requestInput$2.invokeSuspend(MiraiConsoleImplementationPure.kt:103)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:6

以上遇到的问题是使用miraiOK中产生的，不知道具体原因是什么，怀疑是各个jar版本之间冲突导致的？
求大神解答，希望能找到一个稳定的jar包组合……感谢作者！

**Comment by zkonikishi** [comment]
昨天晚上突然出现的问题，已放弃去64位了

**Comment by Brioal** [comment]
在服务器直接运行不会出现这个问题,但是使用nohup 之后就会出现,不知道咋解决了

**Comment by duanluan** [comment]
> 在服务器直接运行不会出现这个问题，但是使用 nohup 之后就会出现，不知道咋解决了

不用管这个错误。
nohup ./mcl > /dev/null &
